
server:
  ip: localhost
  port: 9000

#Spring
spring:
  main:
    allow-circular-references: true #因循环引用导致启动时报错的问题
  datasource:
    #1.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acs?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 3
      min-idle: 3
      max-active: 10
      #配置获取连接等待超时的时间
      max-wait: 60000
  redis:
    host: 1.15.87.229
    port: 6379
    password: 123
    database: 1





mybatis:
  mapper-locations: classpath:mapper/*.xml #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



files:
  upload:
    path: /Users/hope4cc/Documents/EasyExcelDemo/files/
    #    path: /home/springboot/files/



